[project]
name = "investor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pandas>=2.3.3",
    "scipy>=1.14.0",
    "streamlit>=1.54.0",
    "yfinance>=1.2.0",
]
